.PHONY: clean All

All:
	@echo "----------Building project:[ misc - Debug ]----------"
	@cd "misc" && "$(MAKE)" -f  "misc.mk"
clean:
	@echo "----------Cleaning project:[ misc - Debug ]----------"
	@cd "misc" && "$(MAKE)" -f  "misc.mk" clean
